### ISSUE TITLE
google shouldnt be in the list of bots

### ISSUE THREAD

**Issue by mojzis** [MWers/prerender-varnish#1]
see discussion on [official prerender nginx](https://gist.github.com/thoop/8165802) - google should come because it wants to :) and it sends the escaped fragment ...

**Comment by MWers** [comment]
Thanks for the heads up! :+1: I'll update it when I get a sec.

**Comment by MWers** [comment]
Fixed in commit c3220638d6320566589dc86408f2c97a5c53ed1e, thanks @mojzis!
